* lein-rpmbuild

A Leiningen plugin to build project into RPM package.

** Requirements

Make sure you have =rpm-build= installed.
You can install it by running below command in your CentOS/RHEL:

  : yum install -y rpm-build


To use git log as RPM's changelog, you need to use git version 2.6.0 or above.
Use below commands to update the git package to the latest version in your CentOS/RHEL:

  : sudo yum remove -y git
  : sudo yum -y install https://centos7.iuscommunity.org/ius-release.rpm
  : sudo yum -y install git2u-all



** Insatllation

Add the following dependency to the =:plugins= vector of your =project.clj=.

[[https://clojars.org/lein-rpmbuild][https://clojars.org/lein-rpmbuild/latest-version.svg]]


** Usage

Add parameters in your =project.clj=, like this:

#+BEGIN_SRC: clojure
(defproject my-awesome-project "1.1.1"
  :plugins [[carlzhc/lein-tar "3.3.0"
            [lein-rpmbuild "X.X.X"]]
  :rpmbuild {:Name  "RPM-PACKAGE-NAME" ;; Default is the project name.
             :Version "X.X.X"          ;; Default is the project version.
             :Release "1"              ;; Default is "1%{?dist}".
             :Source1 "PATH-TO-SOURCE" ;; Additional sources, support from Source1 to Source9.
             :Requires ["RPM" ...]     ;; Dependencies of other RPM packages.
             :Prefix "PATH"            ;; Destination directory of installation.
             :%prep   "COMMANDS TO UNPACK THE SOURCES"    ;; Default is "%autosetup -v".
             :%build  "COMMANDS TO BUILD PROJECT"         ;; Default is no command to run.
             :%install "COMMANDS TO INSTALL FILES"        ;; Default is to copy all files in BUILDROOT folder into RPM.
             :%files ["PATH-TO-FILE" ...]                 ;; Files which need to be packed to RPM.
             :%doc ["FILE-NAME" ...]                      ;; Files to be packed as documentation, need to be in "pkg/" folder.
             :%config ["FILE-NAME" ...]                   ;; Files to be packed as configuration.
             :%pre  "COMMANDS TO RUN IN %pre SECTION"     ;; Default is no command to run.
             :%post "COMMANDS TO RUN IN %post SECTION"    ;; Default is no command to run.
             :%changelog ["RPM BUILD CHANGE LOG 1" ...] or [:gitlog latest-log-number]
                                                          ;; When using :gitlog, it will get git log as RPM change log.
             :%define [["VAR-NAME" "VAR-VALUE"] ...]      ;; Define additional macros
             :%global [["VAR-NAME" "VAR-VALUE"] ...]      ;; Define additional global macros
             :%undefine ["VAR-NAME" ...]                  ;; Undefine macros
   })
#+END_SRC

To build RPM package, run:

- Build binary package only:
  : lein rpmbuild -tb

- Build source package only:
  : lein rpmbuild -ts

- Build both binary and source packages:
  : lein rpmbuild -ta

- Create rpm spec file only:
  : lein rpmbuild -spec

The SPEC file is created in =pkg= folder, and the RPM packages are generated in =~/rpmbuild/RPMS/= folder.

** License

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html.
